---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: ubuntu
lint: |
  yamllint .
platforms:
  - name: {{ cookiecutter.role_name }}-ubuntu-bionic
    image: ubuntu:bionic
    # command: /lib/systemd/systemd
    # privileged: true
  - name: {{ cookiecutter.role_name }}-ubuntu-xenial
    image: ubuntu:xenial
    # command: /lib/systemd/systemd
    # privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
  lint: |
    ansible-lint
verifier:
  name: testinfra
  lint: |
    flake8
